CLUSTER_NAMES = {
    "1": "Cluster 1 - Law",
    "2": "Cluster 2 - Business, Hospitality & Related",
    "2A": "Cluster 2A - Business, Office & Related",
    "2B": "Cluster 2B - Hospitality & Related",
    "3": "Cluster 3 - Social Sciences & Related",
    "3A": "Cluster 3A - Communication & Media",
    "3B": "Cluster 3B - English & Communication",
    "3C": "Cluster 3C - Kiswahili & Communication",
    "3D": "Cluster 3D - Psychology & Counselling",
    "3E": "Cluster 3E - Fine Arts & Film",
    "4": "Cluster 4 - Geosciences & Related",
    "4A": "Cluster 4A - Geospatial & Geomatic Engineering",
    "4B": "Cluster 4B - Mining, Hydrology & Geoscience",
    "5": "Cluster 5 - Engineering & Related",
    "5A": "Cluster 5A - Specialized Engineering (Auro/Chemical/etc)",
    "5B": "Cluster 5B - Analytical & Industrial Chemistry",
    "5C": "Cluster 5C - Renewable Energy & Instrumentation",
    "5D": "Cluster 5D - Agricultural & Biosystems",
    "5E": "Cluster 5E - Electrical, Medical & Industrial Technology",
    "5F": "Cluster 5F - Education in Technology",
    "6": "Cluster 6 - Architecture, Building Construction & Related",
    "6A": "Cluster 6A - Architecture & Quantity Surveying",
    "6B": "Cluster 6B - Planning & Construction Management",
    "6C": "Cluster 6C - Real Estate & Land Admin",
    "7": "Cluster 7 - Computing, IT & Related",
    "7A": "Cluster 7A - Computer Science & Software Engineering",
    "7B": "Cluster 7B - Applied Statistics & Computing",
    "7C": "Cluster 7C - IT & Business Computing",
    "8": "Cluster 8 - Agribusiness & Related",
    "8A": "Cluster 8A - Agricultural Economics & Agribusiness",
    "9": "Cluster 9 - General Science",
    "9A": "Cluster 9A - Basic Science",
    "9B": "Cluster 9B - Biological Sciences & Biotechnology",
    "9C": "Cluster 9C - Physics & Applied Physics",
    "9D": "Cluster 9D - Chemistry & Environmental Chemistry",
    "10": "Cluster 10 - Mathematics & Related",
    "10A": "Cluster 10A - Accountancy & Finance",
    "10B": "Cluster 10B - Economics & Statistics",
    "10C": "Cluster 10C - Actuarial Science & Finance",
    "11": "Cluster 11 - Clothing, Fashion & Textile",
    "11A": "Cluster 11A - Fashion Design & Interior Design",
    "12": "Cluster 12 - Sports & Related",
    "12A": "Cluster 12A - Sports Science & Management",
    "13": "Cluster 13 - Health Sciences & Related",
    "13A": "Cluster 13A - Medicine, Surgery & Dentistry",
    "13B": "Cluster 13B - Pharmacy & Nursing",
    "13C": "Cluster 13C - Public Health & Lab Science",
    "13D": "Cluster 13D - Veterinary Medicine",
    "13E": "Cluster 13E - Biostatistics & Community Health",
    "13F": "Cluster 13F - Biomedical Science",
    "13G": "Cluster 13G - Medical Informatics & Health Records",
    "14": "Cluster 14 - Social Work & Related",
    "14A": "Cluster 14A - History & Archaeology",
    "15": "Cluster 15 - Agricultural Sciences & Related",
    "15A": "Cluster 15A - Animal Health & Production",
    "15B": "Cluster 15B - Animal Science & Management",
    "15C": "Cluster 15C - Food Science & Nutrition",
    "15D": "Cluster 15D - Food Nutrition & Dietetics",
    "15E": "Cluster 15E - Food Technology & Quality",
    "15F": "Cluster 15F - Environmental Science & Management",
    "15G": "Cluster 15G - Natural Resource Management",
    "16": "Cluster 16 - Geography & Environmental Sciences",
    "16A": "Cluster 16A - Geography & Natural Resource Management",
    "17": "Cluster 17 - French, German & Related",
    "17A": "Cluster 17A - French & German Linguistics",
    "18": "Cluster 18 - Music & Related",
    "18A": "Cluster 18A - Music & Musical Technology",
    "19": "Cluster 19 - Education (Arts/Science) & Related",
    "19A": "Cluster 19A - Education (Arts)",
    "19B": "Cluster 19B - Education (Early Childhood)",
    "19C": "Cluster 19C - Education (Special Needs)",
    "19D": "Cluster 19D - Education (Physical Education)",
    "19E": "Cluster 19E - Education (Home Science)",
    "19F": "Cluster 19F - Education (Visual & Performing Arts)",
    "19G": "Cluster 19G - Education (French)",
    "19H": "Cluster 19H - Education (German)",
    "19I": "Cluster 19I - Education (Music)",
    "19J": "Cluster 19J - Education (Agriculture)",
    "19K": "Cluster 19K - Education (Computer Studies)",
    "20": "Cluster 20 - Religious & Theological Studies",
    "20A": "Cluster 20A - Biblical & Islamic Studies",
}
