[phases.setup]
nixPkgs = ["python3", "postgresql_16.dev", "gcc"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

# Do NOT run migrate here because the DB is unreachable during Docker build
[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

# Run migrations here (Railway Release Phase has DB access)
[phases.release]
cmds = ["python manage.py migrate --noinput"]

[deploy]
startCmd = "gunicorn gradpulse.wsgi:application --log-file -"
