# Generated by Django 5.0.14 on 2026-03-20 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('items_found', models.IntegerField(default=0)),
                ('items_saved', models.IntegerField(default=0)),
                ('items_skipped', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('opportunities', 'Internships & Jobs'), ('events', 'Events'), ('youth_programs', 'Youth Programs'), ('credentials', 'Micro-Credentials'), ('qualifications', 'Professional Qualifications'), ('simulations', 'Simulation Scenarios')], max_length=50)),
                ('sector', models.CharField(choices=[('government', 'Government'), ('ngo', 'NGO'), ('private', 'Private'), ('public', 'Public'), ('international', 'International'), ('academic', 'Academic')], default='private', max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(max_length=1000)),
                ('url_hash', models.CharField(db_index=True, max_length=32, unique=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('salary', models.CharField(blank=True, max_length=255, null=True)),
                ('job_type', models.CharField(blank=True, max_length=255, null=True)),
                ('course_tags', models.JSONField(blank=True, default=list, help_text='List of relevant course names')),
                ('year_tags', models.JSONField(blank=True, default=list, help_text='List of relevant year levels (1-4)')),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('imported', 'Imported')], default='pending', max_length=20)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('imported_by', models.ForeignKey(blank=True, limit_choices_to={'portal_type': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scraped_at'],
            },
        ),
    ]
