# Generated by Django 5.0.14 on 2026-03-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeditem',
            name='source_type',
            field=models.CharField(choices=[('opportunities', 'Internships & Jobs'), ('events', 'Events'), ('youth_programs', 'Youth Programs'), ('credentials', 'Micro-Credentials'), ('qualifications', 'Professional Qualifications'), ('simulations', 'Simulation Scenarios'), ('scholarships', 'Scholarships')], max_length=50),
        ),
    ]
