# Generated by Django 5.0.14 on 2026-03-19 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_simulation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='content_url',
            field=models.URLField(blank=True, help_text='Link to external scenario content or interactive video'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'portal_type': 'employer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_simulations', to=settings.AUTH_USER_MODEL),
        ),
    ]
