# Generated by Django 5.0.14 on 2026-03-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0004_professionalqualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation',
            name='content_url',
        ),
        migrations.AddField(
            model_name='simulation',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='simulation',
            name='json_content',
            field=models.JSONField(blank=True, help_text='Stores AI-generated scenario JSON', null=True),
        ),
    ]
