# Generated by Django 5.0.14 on 2026-03-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admission_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
