# Generated by Django 5.0.14 on 2026-03-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_admission_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='grade_level',
            field=models.CharField(blank=True, help_text='e.g. Grade 7, Form 4', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_category',
            field=models.CharField(blank=True, choices=[('jss', 'Junior Secondary (Grade 7-9)'), ('sss', 'Senior Secondary (Form 1-4)'), ('graduate', 'KCSE Graduate')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='target_career',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='portal_type',
            field=models.CharField(choices=[('student', 'Student'), ('employer', 'Employer'), ('unismart', 'UniSmart (High School & Careers)')], default='student', max_length=20),
        ),
    ]
