# Generated by Django 5.0.14 on 2026-03-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_grade_level_customuser_student_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniSmartResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF Document'), ('link', 'External Link'), ('video', 'Video Guide')], default='pdf', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='unismart/resources/')),
                ('url', models.URLField(blank=True, help_text='Link if not a file', null=True)),
                ('category', models.CharField(choices=[('jss', 'Junior Secondary (Grade 7-9)'), ('sss', 'Senior Secondary (Form 1-4)'), ('graduate', 'KCSE Graduate')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_mentor',
            field=models.BooleanField(default=False, help_text='Available to mentor UniSmart students'),
        ),
    ]
