# Generated by Django 5.0.14 on 2026-03-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_cluster_points_customuser_kcse_results_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniSmartMasterCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('level', models.CharField(choices=[('degree', 'Degree'), ('tvet', 'TVET / Diploma')], default='degree', max_length=20)),
                ('cluster_group', models.CharField(blank=True, max_length=100)),
                ('min_points', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('description', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True, help_text='Subject requirements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'UniSmart Master Course',
                'ordering': ['name'],
            },
        ),
    ]
