# Generated by Django 5.0.14 on 2026-03-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_opportunity_poster_alter_opportunity_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='external_link',
            field=models.URLField(blank=True, help_text='Link to apply externally if not using GradPulse'),
        ),
    ]
