# Generated by Django 5.0.14 on 2026-03-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0004_opportunity_external_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='external_company_name',
            field=models.CharField(blank=True, help_text='Name of organization if not registered on GradPulse', max_length=200),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='type',
            field=models.CharField(choices=[('internship', 'Internship'), ('job', 'Full-time Job'), ('part_time', 'Part-time'), ('freelance', 'Freelance'), ('attachment', 'Industrial Attachment'), ('volunteer', 'Volunteer'), ('funding', 'Funding / Grants / Loans')], default='internship', max_length=20),
        ),
    ]
